### ISSUE TITLE
Entrega de consignas

### ISSUE THREAD

**Issue by jiperdiguero** [frlp-utn-is-2018/orderingg#11]
Hola Rodrigo,

te escribo porque somos varios los alumnos que aún no hemos recibido las consignas luego de haber enviado el mail con la conformación del grupo.

Quedamos a la espera
Julian Perdiguero
mail: jperdiguero@arba.gov.ar

**Comment by RodrigoJacznik** [comment]
Hola, Julian.

Ya fueron entregadas las consignas. Si no las recibiste avísanos.

Cierro este issue.
