### ISSUE TITLE
Problemas para iniciar la aplicación web

### ISSUE THREAD

**Issue by jiperdiguero** [frlp-utn-is-2018/orderingg#13]
Hola;

hemos instalado con mis compañero de grupo los progrmas Python, Sqlite y Flask tal cual se indicó en readme del repo. El problema se presenta a **la** hora de correr orderingg.py en la dirección 127.0.0.1:5000 se muestra un AVM de producto que no permite agregar. El error en la consola donde corre Python es el siguiente:

**File "C:\Users\jperdiguero\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: order [SQL: 'SELECT "order".id AS order_id \nFROM "order" \nWHERE "order".id = ?'] [parameters: ('1',)] (Background on this error at: http://sqlalche.me/e/e3q8)**

Que puede estar sucediendo?
Saludos Julian

**Comment by RodrigoJacznik** [comment]
Hola,

Les falto inicializar la base de datos. 

- En linux o macOs:

```
export FLASK_APP=orderingg.py
flask db upgrade
python fixture.py
```

En windows

- con cmd

```
set FLASK_APP=orderingg.py
flask db upgrade
python fixture.py
```

- PowerShell

```
$env:FLASK_APP="orderingg.py"
flask db upgrade
python fixture.py
```
