### ISSUE TITLE
Pasos para subir un cambio

### ISSUE THREAD

**Issue by Alexissiminkowich** [frlp-utn-is-2018/orderingg#21]
Buen día.

Quería que me asesores con los pasos a seguir para realizar cualquier cambio, a ver si me estoy salteando algún paso:

1º Realizo los cambios pertinentes en el archivo (ej: cambios en el archivo orders.html usando Sublime)
2º Corroboro los cambios: Flask run y veo en 127.0.0.1:5000 los cambios, a ver si quedaron bien.
3º Si esta todo bien, subir los cambios:

git branch feature/#N
git checkout feature/#N
git status : me mostrara en rojo un archivo, el que modifique
git add (nombre del archivo)
git status : el nombre aparecerá en verde, listo para commitear
git commit : le aparece para agregar un comentario, o commit así:
git commit -m "mensaje" : se commitea de una con ese comentario
git status nos indica que hay cambios para pushear
git push : si es la primera vez, me pide usuario y contraseña del GitHub
git checkout dev : vuelvo a dev
git merge feature/#N : mergeo los cambios del feature/#N a dev

Me faltaría o sobra algo?

Gracias!!

**Comment by RodrigoJacznik** [comment]
Hola Alexis,

Te comento entre lineas:

```
git branch feature/#N
git checkout feature/#N
```

En general el branch se realiza antes de hacer los cambios. Estos 2 comandos los podes resumir como: `git checkout -b feature/#N`

```
git status
git add
git status
```
Esto esta bien

```
git commit
git commit -m "mensaje"
```

No hace falta realizar estos 2 comandos, con 1 de los dos alcanza

```
git status
git push
git checkout dev
git merge feature/#N
```

Esto esta bien. Te falto hacer un push para que el merge quede en el repositorio remoto.

Saludos

**Comment by Alexissiminkowich** [comment]
Buenisimo, va queriendo entonces.

Los 2 estilos de commit los puse para acordarme de que hay 2 formas de hacerlo.

En el ultimo paso:

git status
git push
git checkout dev
git merge feature/#N

Ahi hice un push, me dijiste que faltaria un push mas al final de todo?

**Comment by RodrigoJacznik** [comment]
Claro, falta el push del merge
