### ISSUE TITLE
Consulta Boton borrar

### ISSUE THREAD

**Issue by EzequielMartin** [frlp-utn-is-2018/orderingg#22]
Buenas noches,
estaba intentando hacer el punto de agregar un boton que borre las ordenes de la base de datos pero no lo puedo hacer andar. El backend para este punto no esta implementado asi que lo tendria que implementar yo.
Queria consultar de donde podria leer para hacer la parte en javascript. Hice el tutorial que nos pasaron de flask y entendi como agregar y eliminar elementos de la base de datos pero tambien tengo que hacer las funciones js y no cazo una.

Muchas gracias.

**Comment by RodrigoJacznik** [comment]
Hola Ezequiel. Pudiste agregar el botón a la tabla?
Si no pudiste, fíjate que en el archivo `app/templates/orders.html`  hay un script con id `table-template`. En ese script se define el template de la tabla. Para agregar el botón vas a tener que agregar una nueva columna.

Cuando ya tengas el botón de eliminar producto en cada fila de la tabla, le vas a tener que agregar un listener para el evento click. Te dejo [documentación](https://developer.mozilla.org/es/docs/Web/API/EventTarget/addEventListener) al respecto.
El handler de este evento tiene que invocar al endpoint del backend.

Si necesitas más ayuda, avisame.
Saludos.

**Comment by EzequielMartin** [comment]
Ahi pude hacer andar el boton, tuve que usar un onclick directamente en el boton ya que intente agregarle un Event Listener pero no lo pude hacer andar.
Cuando intentaba agregarle el event listener el getElementById me retornaba null, osea era como que no tenia ningun elemento con ese id. Por ejemplo tenia el boton : 
`<button id="botonBorrar">Borrar</button>`
y hacia:
`boton = document.getElementById("botonBorrar")` para despues hacer `boton.addEventListener("click", .....)`
pero ya el getElementById me retornaba null asi que no podia hacer lo otro tampoco. 
Creo que es porque todos los botones que se van creando en las filas de la tabla siempre tienen el mismo id (botonBorrar en mi caso ) entonces el getElementById no sabe cual de todos devolver.
Para lo de js intente adaptar mucho las funciones que ya habian definido ustedes a lo que yo necesitaba pero me quedaron bastante dudas de que hacian algunas lines de codigo particulares, osea entendia lo que hacian en general las funciones pero algunas lineas de codigo las copie sin entender mucho que hacian, si no hay problema la proxima clase consultaria algunas dudas.

Muchas gracias por la ayuda!

**Comment by RodrigoJacznik** [comment]
Hola Ezequiel. Como va?

`getElementById` no retorna el elemento porque es muy probable que lo ejecutes antes de que el propio elemento exista. No hay problema con que uses `onclick` directamente en el elemento en este caso en particular.

No hay drama, el lunes lo vemos.
Saludos.
