### ISSUE TITLE
Actualizar a la Version 2

### ISSUE THREAD

**Issue by Alexissiminkowich** [frlp-utn-is-2018/orderingg#23]
Consulta con respecto al comando git remote. No recuerdo los pasos para poder actualizar nuestro repo a la v2 del origin. Esto mantiene los cambios nuestros no?

**Comment by RodrigoJacznik** [comment]
Hola Alexis, como estas?

Son varios los comandos que hay que ejecutar para sincronizar su repositorio con el nuestro.

Primero tenes que agregar el remote de nuestro repositorio en su fork. [Acá te dice como hacerlo](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
Después tenes que sincronizar. Te dejo otro [link](https://help.github.com/articles/syncing-a-fork/)

Es muy probable que tengas que realizar un merge. Procura mantener tus cambios y los nuestros al resolver el conflicto. Especialmente el cambio del handler del evento onclick del botón para agregar un nuevo producto.

Saludos.

**Comment by Alexissiminkowich** [comment]
Dale genial, gracias!! voy paso a paso y cualquier cosa te consulto. 

Saludos

**Comment by RodrigoJacznik** [comment]
Enviame la salida de `git log` por favor.

**Comment by Alexissiminkowich** [comment]
Equipo@Equipo-PC MINGW32 ~/Desktop/ING DE SOFTWARE/orderingg (dev)
$ git log
commit e80f799e2ec582a36bc7670f4040890291f041a2 (HEAD -> dev, origin/dev, origin/HEAD, arreglo_boton_no_abria)
Author: unknown <alexis.frlp@gmail.com>
Date:   Fri Apr 27 18:40:29 2018 -0300

    arreglo_boton_no_abria

commit d03cdb40bbf42f71deecabf9c9c2fd08bd6b4fde (origin/feature/cambiarbotton)
Author: Rorromiguel <maiguel.rodrigo@gmail.com>
Date:   Fri Apr 27 10:39:34 2018 -0300

    commit de rodrigo q cambia el botton

commit 2d5b3c6a7d6a932f4981b77deb51bc8d253118c2
Author: ¨gero120976¨ <38442570+Gero120976@users.noreply.github.com>
Date:   Thu Apr 26 19:17:40 2018 -0300

    modificado por Gero

commit 300dd5e44b0e475ed6d1194f879ff7fcd8c57ef2
Author: unknown <alexis.frlp@gmail.com>
Date:   Mon Apr 23 22:48:46 2018 -0300

    Tabla Stripped

**Comment by RodrigoJacznik** [comment]
Fijate que me parece que estas queriendo sincronizar master y no se si le hiciste un pull de ese branch.
Intenta lo siguiente.

`git checkout dev`
`git pull upstream master`

**Comment by Alexissiminkowich** [comment]
Ahi lo hice, actualizo, luego tiro git status y sale todo bien. Pero me fijo y los cambios no estan... osea el nuevo color del boton, la tabla striped... esta como en un principio

**Comment by RodrigoJacznik** [comment]
No te tiro algún conflicto sin resolver en el merge?

**Comment by Alexissiminkowich** [comment]
Equipo@Equipo-PC MINGW32 ~/Desktop/ING DE SOFTWARE/orderingg (dev)
$ git pull upstream master
From https://github.com/frlp-utn-is-2018/orderingg
 * branch            master     -> FETCH_HEAD
Already up to date.

Asi me tiro.
Ahi me fije, si me paro en dev, si puedo ver los cambios que hicimos nosotros.

Me faltaria algo? push a nuestro repo?

**Comment by RodrigoJacznik** [comment]
No, te falta hacer un merge de dev con master.

**Comment by Alexissiminkowich** [comment]
seria así?

git checkout dev
git merge master

**Comment by RodrigoJacznik** [comment]
exacto

**Comment by RodrigoJacznik** [comment]
origin/master
