### ISSUE TITLE
problema de merge

### ISSUE THREAD

**Issue by SantiClausen** [frlp-utn-is-2018/orderingg#24]
Acabo de realizar un punto, pero estoy confundido con el tema de merging.

Despues de realizar el punto, hice lo siguiente:
git push origin <nombre rama>
git checkout dev
git merge <nombre rama>
git push origin dev

Lo que hizo eso es mostrar una rama nueva que sale desde dev, pero en vez de que la rama salga y vuelva de nuevo a dev, la rama sigue desconectada, y ahora tiene 2 tags, "dev" y el nombre de la rama. ¿Como hago para que la rama del punto vuelva para dev?

**Comment by RodrigoJacznik** [comment]
Hola, como va? Te olvidaste de indicar con que rama querías mergear.
Por ejemplo, si queres mergear el branch feature/#1 con dev:

`git checkout dev`
`git merge feature/#1`

Y luego hacer un push.
Saludos.
