### ISSUE TITLE
Boton Borrar - Backend

### ISSUE THREAD

**Issue by Alexissiminkowich** [frlp-utn-is-2018/orderingg#25]
Buenos días

Me rompi un poco la cabeza leyendo todo el código, pero esa parte sigue siendo difícil jeje. 

Logre agregar el botón en la tabla, sin problemas.
La cuestión es como genero la función borrar producto de la orden de compra (o disminuir cantidad, también pensaba las diferentes formas que se podría borrar).
Una ayuda para la programación de la funcionalidad? Igualmente seguire intentando leyendo las otras funcionalidades en el /js/api.js ahi vi que esta la funcionalidad agregar producto

Saludos

**Comment by RodrigoJacznik** [comment]
Hola Alexis.

Para eliminar un producto de una orden tenes que agregar el método `HTTP DELETE` al endpoint `/order/<pk_order>/product/<pk_product>`. Esto se agrega en el archivo `routes.py`.
El producto hay que eliminarlo desde el backend.

Cualquier cosa avísame y te doy una mano

**Comment by Alexissiminkowich** [comment]
Llevo hecho lo siguiente y me tira error en el endpoint en la linea de borrar... busque pero no encuentro la sintaxis del DELETE:

En orders.html tengo el botón en la tabla:

<td><button class="button" style="background-color:#F91F05" onclick="refs.api.deleteProduct()">
<span class="icon"><i class="fas fa-ban"></i></span>
<span>Borrar linea</span>
</button></td>

En api.js hice la función deleteProduct:

    function deleteProduct(product) {
        return fetch(`/order/${ orderId }/product`,
            {
                method: 'DELETE',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
                body: data
            }
        ).then(function toJson(r) {
            return r.json();
        });
    }

En routes.py tengo la rutina DELETE:

@app.route("/order/<pk_order>/product/<pk_product>", methods=['DELETE'])
def order_product_detail(pk_product):
    """
    Borra un producto de una Orden
    """
        DELETE "/order/<pk_order>/product/<pk_product>"
        db.session.commit()
        return jsonify(order_product.serialize)

Supongo que en la linea DELETE "/order/<pk_order>/product/<pk_product>" es donde esta el final.
Hice algo de mas o de menos? Donde puedo leer para saber como es la sintaxis del DELETE?

Saludos!!
Alexis

**Comment by ferraradamian** [comment]
Buenas,
Yo estoy trabado en lo mismo, voy a intentar algo como lo que hiciste Alexis.

Saludos

**Comment by RodrigoJacznik** [comment]
Buenas.
Fíjense que el endpoint `/order/<pk_order>/product/<pk_product>` ya tiene un handler (una función) en el archivo routes.py, no hay que agregar otra función, con un if que maneje cada método alcanza.

El js está más o menos bien. El endpoint tiene que respetar lo que está en el backend. En este caso tendría que ser algo así: `/order/1/product/1`.

Para leer pueden fijarse en la doc de flask o en la doc de sqlalchemy (el orm que usamos).

Cualquier cosa mañana les doy una mano mas, ahora estoy desde el celular.

Saludo.

**Comment by ivanduva** [comment]
Buenas chicos. Si bien no está "mal" que hagan otro endpoint, lo que dice Rodri sería lo más lógico porque el endpoint `/order/<pk_order>/product/<pk_product>` ya tiene toda la información que ustedes necesitan para borrar el producto, que es el id de la orden y el id del producto.
El método de ese endpoint es order_product_detail, tienen que permitirle aceptar requests del tipo DELETE y agregar un if para ese caso. Para hacer lo primero, tienen que cambiar el decorator que está encima del método, de la siguiente manera:
`@app.route("/order/<pk_order>/product/<pk_product>", methods=['GET', 'PUT', 'DELETE'])`
Luego, si se fijan, ese método ya obtiene el objeto OrderProduct que ustedes necesitan borrar. En el if que se fija si el tipo de request es GET, hay un else que toma los casos del tipo de request PUT porque hasta ahora sólo se permite obtener (GET) o modificar (PUT) un producto dentro de una orden. Para agregar el borrado ustedes tienen que agregar otro caso a ese if: `if request.method == 'DELETE'`. En python no es necesario chequear la nueva condición dentro del else, sino que tiene un operador específico para esos casos: elif. Entonces el código quedaría como sigue:
`    if request.method == 'GET':`
`        return jsonify(order_product.serialize)`
`    elif request.method == 'DELETE':`
`        [SU CODIGO PARA BORRAR]`
`    else:`
`    ....`

Avisen si no quedó claro,
Saludos

**Comment by ferraradamian** [comment]
Buenas tengo un problema no puedo llamar a la funcion js que cree, me dice que no esta definida
Cannot read property 'deleteProduct' of undefined
La llamo desde el button asi:  
`onclick="refs.api.deleteProduct()"`
La agregue en api.js
 Saludos!!

**Comment by Alexissiminkowich** [comment]
Realice los cambios y los guarde en el ultimo commit, ya no tira ningún error, la aplicación inicia bien, pero lo unico es que no carga la tabla de articulos. Ejecuto todos los iniciadores:

export FLASK_APP=orderingg.py
flask db upgrade
python fixture.py
export FLASK_DEBUG=1
flask run

Pero nada... sale solo el titulo y el botón de Agregar (que tampoco abre el modal).

Desde ya muchas gracias por la ayuda!!

**Comment by RodrigoJacznik** [comment]
@ferraradamian Si agregaste la función en el archivo `api.js` fíjate que en el return este el nombre de la función que agregaste y luego el `onclick` queda `onclick=API.deleteProduct(id)`.
Le agregue id a la signature de la función porque de alguna forma debes indicar que producto queres borrar.

@Alexissiminkowich estos pasos:
```
flask db upgrade
python fixture.py
```

Solo se tienen que realizar cuando clonan el proyecto (o actualizan las tablas de la DB, cosa que no pasa en ningún ejercicio).
Es probable que el error este en otro lado. Abrí la consola y fíjate que no tengas ningún error en el js

**Comment by ferraradamian** [comment]
Buenas, tengo la funcion

`   function deleteProduct(product) {
        return fetch(`/order/${ orderId }/product`,
            {
                method: 'DELETE',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
                body: data
            }
        ).then(function toJson(r) {
         return r.json();
        });
    }`
No entiendo de donde sacar el orderId, el ide del producto lo saco de la tabla y lo paso como parámetro
Saludos!!

**Comment by ferraradamian** [comment]
Buenas, tengo la funcion:
`  function deleteProduct(orderId,productId) {
     const data = JSON.stringify({ product: productId })
        return fetch(`/order/${ orderId }/product/${ productId }`,
            {
                method: 'DELETE',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
                body: data
            }
        ).then(function toJson(r) {
         return r.json();
        });
    }`
 Y en router.py
`@app.route("/order/<pk_order>/product/<pk_product>", methods=['GET', 'PUT', 'DELETE'])
def order_product_detail(pk_order, pk_product):
    """
    Obtiene un producto de una orden y modifica un producto de una orden

    Si no se encuentra la orden, se responde con un 404.
    Si no se encuentra el producto, se responde con un 404
    """

    order_product = OrderProduct.query.filter(and_(OrderProduct.order_id==pk_order, OrderProduct.product_id==pk_product)).all()[0]

    if (not order_product):
        return jsonify({ 'error': 'not-found' }), 404

    if request.method == 'GET':
        return jsonify(order_product.serialize)
    elif request.method == 'DELETE':
        print('Eliminar')

        return jsonify(order_product.serialize)
    else:
        new_quantity = request.get_json()['quantity']
        new_product = request.get_json()['product']

        if (new_quantity):
            order_product.quantity = new_quantity
        if (new_product):
            order_product.product = Product.query.get(new_product)
            order = Order.query.get(pk_order)
            order.products.append(order_product)
        db.session.commit()
        return jsonify(order_product.serialize)`
No tengo idea de python, así que no se como eliminar el producto, paso  producId como parametro, pero no se como lo borro ese producto de la orden en la base.

Saludos!!

**Comment by RodrigoJacznik** [comment]
Te edite el comentario par que tenga resaltado de sintaxis y sea mas fácil de leer.
Para eliminar podes usar

```python
# Lo serializo antes de eliminarlo porque si no rompe
order_product_json = order_product.serialize

db.session.delete(order_product)
db.session.commit()
return jsonfi(order_product_json)
```

Espero que te sea de ayuda. Saludos
