### ISSUE TITLE
Botón editar

### ISSUE THREAD

**Issue by luis-sama** [frlp-utn-is-2018/orderingg#27]
Buenas tengo un problema con el botón editar de producto. No estoy seguro de como traer de la bd el producto y el id del producto. Ésta es la función editar:

```
function onEditProduct() {
        API.editProduct(1, state.selectedProduct.id, state.quantity, state.selectedProduct.name)

```

El error que me tira es 

`TypeError: state.selectedProduct is null`

**Comment by RodrigoJacznik** [comment]
Hola,

Lo que deberías hacer es crear una función que cargue el producto en el modal y esa funciona agregarla en el template.
Por ejemplo

```html
<tr>
    <td>{{ id }}</td>
    <td>{{ name }}</td>
    <td>{{ price }}</td>
    <td>{{ quantity }}</td>
    <td>{{ totalPrice }}</td>
    <td>
        <button onClick="edit({ id: {{ id }}, quantity: {{ quantity }} })">
            <i class="fa fa-edit"></i>
        </button>
    </td>
</tr>
```

Luego la función edit debería cargar el producto en el modal. La función edit la podes agregar en index.js

```javascript
function edit(product) {
    const $quantity = document.querySelector('#quantity');
    const $select = document.querySelector('#select select');

   $quantity.value = product.quantity;
   $select.value = product.id;

   state.quantity. = product.quantity;
   state.selectedProduct = product;

   // Abre el modal en forma de edición;
   refs.modal.open(edit);
}

window.edit = edit;
```


Luego tenes que attachar un listener al botón editar del modal que llame al backend.

Si necesitas una mano avisame.
Saludos.
