### ISSUE TITLE
No aparecen los articulos

### ISSUE THREAD

**Issue by Alexissiminkowich** [frlp-utn-is-2018/orderingg#28]
Lo que comentaba en el otro issus.
No me carga los articulos en la tabla (o tarda mucho y sale... a veces)

Durante la ejecucion, en el git bash me sale asi cuando recargo la pagina.

127.0.0.1 - - [02/May/2018 18:42:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2018 18:42:15] "GET /product HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2018 18:42:15] "GET /order/1 HTTP/1.1" 200 -

Eso me esta indicando un error 200 o me equivoco?

**Comment by ivanduva** [comment]
el 200 es el codigo de estado de HTTP que indica que la solicitud está OK (https://developer.mozilla.org/es/docs/Web/HTTP/Status). Así que no hay problema ahí
Intenta borrar el caché del browser y supongo que ahí va a andar

**Comment by Alexissiminkowich** [comment]
Era eso. Borre la cache y los cargo enseguida. Gracias!
