### ISSUE TITLE
Problema con mostrar el nombre del producto en la tabla

### ISSUE THREAD

**Issue by CarlosdAndrade** [frlp-utn-is-2018/orderingg#32]
Hola profesor, no encuentro la forma de poder mostrar el nombre del producto. Gracias por su tiempo

**Comment by RodrigoJacznik** [comment]
Hola carlos fijate que el cuerpo de la tabla te tiene que quedar algo asi:

```html
{{# each products }}
    <tr>
        <td>{{ id }}</td>
        <td>{{ name }}</td>           <!-- Nombre del producto -->
        <td>{{ price }}</td>
        <td>{{ quantity }}</td>
        <td>{{ totalPrice }}</td>
    </tr>
{{/ each }}
```

Saludos.

**Comment by CarlosdAndrade** [comment]
Gracias profe. Hoy a la noche le subimos todo.

El may. 5, 2018 12:10, Rodrigo Jacznik <notifications@github.com> escribió:

Hola carlos fijate que el cuerpo de la tabla te tiene que quedar algo asi:

{{# each products }}
    <tr>
        <td>{{ id }}</td>
        <td>{{ name }}</td>           
        <td>{{ price }}</td>
        <td>{{ quantity }}</td>
        <td>{{ totalPrice }}</td>
    </tr>
{{/ each }}

Saludos.
