### ISSUE TITLE
Problema con el Merge

### ISSUE THREAD

**Issue by CarlosdAndrade** [frlp-utn-is-2018/orderingg#33]
Hola Profesor, me sale lo siguiente cuando hago un git status y no se como seguir
On branch master
Your branch is up to date with 'origin/master'.

All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:

        modified:   README.md
        modified:   app/models.py
        modified:   app/templates/orders.html
La verdad no se como seguir.

**Comment by RodrigoJacznik** [comment]
Hola Carlos,

tenes que usar `git commit` para terminar de resolver el conflicto.

Saludos.
