### ISSUE TITLE
No me toma el nombre de usuario cuando realizo un cambio.

### ISSUE THREAD

**Issue by Rorromiguel** [frlp-utn-is-2018/orderingg#34]
Buenas, la otra vez me paso que un compañero había dejado su rama en dev, y cuando la merge a master, me apareció como si el cambio lo hubiese hecho él. Y recién acabo de hacer el hotfix, y cuando miro la "network" dentro de "Insights" me sale como que el cambio lo realizo "root". ¿porque puede ser esto?

**Comment by RodrigoJacznik** [comment]
Hola, tenes un conflicto en la configuración de tu git.
Lo podes arreglar así:

```
git config --global user.name "Your Name"
git config --global user.email you@example.com
```

Esos 3 commits los anoto que son tuyos, para la próxima actividad procura que esto este resuelto para facilitarnos el trabajo al momento de revisar los repo.

Saludos.

**Comment by Rorromiguel** [comment]
Gracias Rodrigo!
Ya lo arreglé!
