### ISSUE TITLE
tabla de orderingg no aparece

### ISSUE THREAD

**Issue by SantiClausen** [frlp-utn-is-2018/orderingg#44]
Tengo un problema similar a alguien en los issue, pero por alguna razón el código de error que tengo es distinto:

Uncaught SyntaxError: Unexpected token <<
index.js:131 Uncaught ReferenceError: Modal is not defined
    at init (index.js:131)
    at index.js:151
    at index.js:154
:5000/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND)
4(index):21 Uncaught ReferenceError: refs is not defined
    at HTMLButtonElement.onclick ((index):21)

el numero de los at son distintos

**Comment by RodrigoJacznik** [comment]
Hola
No mergeaste bien, te quedaron las marcas de git en el código.

**Comment by SantiClausen** [comment]
como podría resolverlo?

**Comment by RodrigoJacznik** [comment]
Al mergear aparecen conflictos, git los intenta solucionar y cuando no puede hacerlo los tenes que arreglar vos.
Te paso un link con más info: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

Si no lo podes solucionar, pasame la salida de git status.

**Comment by SantiClausen** [comment]
yo tuve un problema haciendo el merge que estuve viendo con los ayudantes la clase pasada, en donde me mostraron como solucionar los problemas del conflictos. Pudimos solucionar los conflictos, pero ahora veo que causo problemas con orderingg.py

y la salida de git status no me muestra nada, mis branchs estan limpios

**Comment by RodrigoJacznik** [comment]
Hace un branch nuevo y pushealo así te pude ayudar mejor.

**Comment by SantiClausen** [comment]
https://github.com/jiperdiguero/orderingg/tree/tablaerror

**Comment by RodrigoJacznik** [comment]
El archivo modal.js tiene un conflicto sin resolver.

**Comment by SantiClausen** [comment]
ahi arregle el conflicto del modal, pero la pagina aun utiliza el modal viejo en vez del modificado

**Comment by SantiClausen** [comment]
ahi vi por que, parece que la consola no esta subiendo los .js

**Comment by RodrigoJacznik** [comment]
Tenes conflictos sin resolver en orders.html. Es probable que ese sea el problema.

**Comment by SantiClausen** [comment]
ahi arregle el orders.html, pero la consola sigue sin subirme los archivos .js
![image](https://user-images.githubusercontent.com/38263254/40551307-e3496890-6012-11e8-8e35-02e417d705c2.png)

**Comment by RodrigoJacznik** [comment]
Actualiza al branch así me lo bajo y pruebo en mi máquina

**Comment by SantiClausen** [comment]
el branch ya fue actualizado con las correcciones

**Comment by SantiClausen** [comment]
un momento, ahi se logro solucionar: Borre cookies y elementos almacenados en la pagina, y ahi se pudieron actualizar los .js. Puedo agregar, modificar y eliminar sin problemas ahora

**Comment by RodrigoJacznik** [comment]
Genial.
Te recomiendo que para desarrollar tengas activado el "deshabilitar cache" desde la consola de desarrollo de chrome y hacer las pruebas con la consola abierta. Te paso un link donde indica como hacerlo https://stackoverflow.com/a/7000899

**Comment by SantiClausen** [comment]
dale muchas gracias
