### ISSUE TITLE
Consulta test metodo http DELETE

### ISSUE THREAD

**Issue by EzequielMartin** [frlp-utn-is-2018/orderingg#46]
Buenas, estaba haciendo el test para probar el delete y queria consultar si esta bien hecho. 
Lo que hice fue agregar un orderProduct a la base de datos, ya que para poder testear borrar algo necesitaba tener algo en la base de datos, y despues guardar el retorno de self.client.delete para ver si se hizo correctamente. El codigo me quedo asi:
    
```
def test_delete(self):
        o = Order(id= 1)
        db.session.add(o)

        p = Product(id= 1, name= 'Tenedor', price= 50)
        db.session.add(p)

        orderProduct = OrderProduct(order_id= 1, product_id= 1, quantity= 1, product= p)
        db.session.add(orderProduct)
        db.session.commit()
        
        resp = self.client.delete('order/1/product/1')

        self.assert200(resp, "Fallo el DELETE")
```

El codigo ya no me tira errores pero por las dudas queria consultar para no entregar algo mal hecho.

Saludos.

**Comment by RodrigoJacznik** [comment]
Esta joya. Además de controlar la respuesta podes fijarte que la base de datos no tenga ese producto.

**Comment by luisuran** [comment]
Lo que hice fué ésto

`def test_borrar_producto(self):
        #Creo un producto
        product = {
            'id': 1,
            'name': 'Tenedor',
            'price': 50,
        }
        self.client.post('/product', data=json.dumps(product), content_type='application/json')

        #Creo una orden
        orden = {
            'id': 1,
        }
        db.session.add(orden)
        
        #Creo una ordenProducto
        orden_producto = {
            'order_id': 1,
            'product_id': 1,
            'product': product,
            'quantity': 15,
        }
        db.session.add(ordenProducto)

        order_product = OrderProduct.query.filter(and_(OrderProduct.order_id==1, OrderProduct.product_id==1)).all()[0]
        db.session.delete(order_product)

        p = Product.query.all()

        #Verifica que el producto se haya borrado correctamente
        self.assertEqual(len(p), 0, "Borrado incorrecto")`

y me tira error en la línea 
order_product = OrderProduct.query.filter(and_(OrderProduct.order_id==1, OrderProduct.product_id==1)).all()[0]

**Comment by RodrigoJacznik** [comment]
Es probable que te falte importar el método _add. Es mejor la solución de Ezequiel

**Comment by luisuran** [comment]
le puse from sqlalchemy import and_ 
El error que me tira es indexError: list out of range

**Comment by RodrigoJacznik** [comment]
Entonces esa línea no te está retornando nada. Es mejor la solución de Ezequiel

**Comment by ivanduva** [comment]
Luis igual fijate que no estas testeando el endpoint, solo estas testeando el borrado. Tenés que llamar al endpoint `/order/<pk_order>/product/<pk_product>/` con el método DELETE.

**Comment by ignacio96** [comment]
Estaria bien agregar esto al final del codigo de Ezequiel como para chequear que la base de datos no tenga ese producto?

self.assertIn(p.id,db.session.query(OrderProduct.product_id).filter_by(order_id=1),"El producto ha sido borrado")

**Comment by ivanduva** [comment]
sisi, exacto. Eso es lo que faltaba

**Comment by EzequielMartin** [comment]
Yo necesitaria agregarselo a mi codigo tambien? Como cuando pregunte si mi codigo estaba bien Rodrigo me dijo que si y que "podia" agregarle eso tambien me lo tome como que no era necesario y no lo hice para no complicarme de gusto. Esta mal si no lo agrego?

**Comment by ivanduva** [comment]
@ignacio96 me di cuenta que el assert correcto ahí sería el `assertNotIn` porque vos tenes que chequear que ese id de producto NO esté en la orden

**Comment by ivanduva** [comment]
@EzequielMartin Está bien igual, pero ya que Ignacio escribió el código, si querés ponelo vos también para que quede mejor. A menos que se te ocurra como hacerlo de otra manera. Lo que hace ignacio ahí con esto: `db.session.query(OrderProduct.product_id).filter_by(order_id=1)` es buscar todos los id de los productos de la orden número 1. Con el `assertNotIn` se chequea que el id del producto creado para el test no se encuentre mas en la lista de ids que retorna lo anterior.

**Comment by ignacio96** [comment]
@ivanduva Yo pense lo mismo, pero la idea no seria que avise cuando el producto se borro? Si uso el assetNotIn el mensaje deberia ser "El producto no se borro" y seria como redundante ya que el otro assert avisa cuando no funciona el delete

**Comment by EzequielMartin** [comment]
Supongo que es porque por ahi el delete te devuelve 200 pero no se borro de la base de datos por algun motivo. Entonces probas que devuelva 200 Y que se borre de la base de datos. La idea es que el test "pase" cuando se hace correctamente lo que queres hacer, en este caso queres que se borre el producto entonces el assert tiene que probar que se borro el producto

**Comment by ivanduva** [comment]
Probaste el test? Si lo haces con el In, tiene que fallar porque el id no va a estar en esa lista.
Así como está el enfoque está mal porque estás chequeando el caso contrario. Vos tenés que probar que efectivamente el producto NO esté en la lista.
En cuanto al mensaje, es el mensaje que tira cuando el assert falla, o sea: "el producto no fue borrado" o algo por el estilo.

**Comment by ivanduva** [comment]
Exacto @EzequielMartin

**Comment by ignacio96** [comment]
Si lo probe y me tiro error, despues lo hice con el notIn y me anduvo
