### ISSUE TITLE
Problema al querer instalar pytest y selenium

### ISSUE THREAD

**Issue by kasspablo** [frlp-utn-is-2018/orderingg#47]
Hola, estoy teniendo problemas al instalar Pytest y Selenium en una mac con python 2.7. De todas las maneras que intente instalarlos, me sale el mismo error:
"Could not fetch URL https://pypi.python.org/simple/pytest/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement pytest (from versions: )
No matching distribution found for pytest"
Ya intente con --trusted-host pero tampoco... y si bajo los archivos, y hago "python setup.py install" por cada archivo que lee, me tira el mismo error...

**Comment by RodrigoJacznik** [comment]
Podes instalar python3? La verdad que no tengo una instalación con python2 y me va a complicar darte soporte.

**Comment by kasspablo** [comment]
Bueno, pude instalar python 3 y se soluciono... ahora tengo los 2 python, y para usar el 3 tengo que crear un entorno virtual, y mientras este habilitado voy a tener python 3 por defecto, y si lo desactivo, vuelvo al python 2... genial gracias!

**Comment by RodrigoJacznik** [comment]
Buenísimo.
