### ISSUE TITLE
Consulta sobre el TotalPrice de Order

### ISSUE THREAD

**Issue by Zeriel** [frlp-utn-is-2018/orderingg#53]
Buenas,

 Estoy haciendo el test para verificar que el precio total calculado en la orden sea el correcto. El código del test que ensamblé hasta ahora es el siguiente:

    def test_totalPrice(self):
        #Creo dos productos y los inserto a la db
        
        o = Order(id= 1)
        db.session.add(o)

        p = Product(id= 1, name= 'Tenedor', price= 50)
        db.session.add(p)
        
        orderProduct = OrderProduct(order_id= 1, product_id= 1, quantity= 3, product= p)
        db.session.add(orderProduct)

        db.session.commit()

        #Obtengo la orden, obtengo su TotalPrice y lo chequeo

        orden= Order.query.get(1)
        totalPrice = orden.orderPrice()
        self.assertEqual(150, totalPrice, "El precio total no se calcula bien")

Al ejecutarlo, me arroja el siguiente error:

        #Obtengo la orden, obtengo su TotalPrice y lo chequeo
        orden= Order.query.get(1)
>       totalPrice = orden.orderPrice()
E       TypeError: 'float' object is not callable

Encaré este test intentado crear un producto con cantidad 3 para, finalmente, obtener el totalPrice calculado en Order para evaluarlo en el assert. En caso que este enfoque sea el correcto, ¿el error que arroja el pytest estaría relacionado con la forma en que accedo al totalPrice?

Gracias.

**Comment by RodrigoJacznik** [comment]
`orden.orderPrice` no es un método, por eso te falla. El resto del test esta bien.

**Comment by Zeriel** [comment]
Ahí pude hacer andar el test, muchas gracias.
