### ISSUE TITLE
Duda sobre Test Selenium

### ISSUE THREAD

**Issue by macadden** [frlp-utn-is-2018/orderingg#55]
En el ejercicio tengo que "hacer un test de integración con Selenium para probar que exista información dentro del modal cuando se abre para editar un producto". Ya pude abrir el modal de deditar pero no sé qué información es la que se quiere que obtenga del modal. ¿La información que se requiere es la cantidad y/o el nombre del producto?

 Este es el código que tengo hasta ahora:

   ```
 def test_InfoModalEditar(self):
        o = Order(id= 1)
        db.session.add(o)

        p = Product(id= 1, name= 'Tenedor', price= 50)
        db.session.add(p)

        orderProduct = OrderProduct(order_id= 1, product_id= 1, quantity= 1, product= p)
        db.session.add(orderProduct)
        db.session.commit()

        driver = self.driver
        driver.get(self.baseURL)

        edit_product_button = driver.find_element_by_xpath('/html/body/main/div[2]/div/table/tbody/tr[1]/td[6]/button[1]')
        edit_product_button.click()  
```

**Comment by ivanduva** [comment]
Exacto, tenés que verificar que los inputs estén completos con la información esperada. Con verificar uno de los dos está bien. Si lo hacés con los dos, mejor.

**Comment by macadden** [comment]
Ya lo pude solucionar, lo hice con los dos. Gracias!!
