### ISSUE TITLE
Error cuando corre test

### ISSUE THREAD

**Issue by luisuran** [frlp-utn-is-2018/orderingg#56]
Hola, estoy queriendo correr un test de integración y me sale éste error:

```
------------------------------------ Captured stderr call ------------------------------------
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/luran/Documentos/Trabajos/orderingg/miEnv/lib/python3.5/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/luran/Documentos/Trabajos/orderingg/miEnv/lib/python3.5/site-packages/werkzeug/serving.py", line 812, in run_simple
    reloader_type)
  File "/home/luran/Documentos/Trabajos/orderingg/miEnv/lib/python3.5/site-packages/werkzeug/_reloader.py", line 267, in run_with_reloader
    signal.signal(signal.SIGTERM, lambda *args: sys.exit(0))
  File "/usr/lib/python3.5/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```
Venía funcionando bien hasta que inicié la la app y cuando volvi a correr el test ya no andaba

**Comment by RodrigoJacznik** [comment]
Hola.
Que comando estás usando? 

No tiene que estar corriendo el servidor de desarrollo.

**Comment by luisuran** [comment]
pytest test/test_e2e.py
Al servidor lo terminé con ctrl+c

**Comment by RodrigoJacznik** [comment]
Proba cerrando la consola, creo que el thread queda corriendo.

**Comment by luisuran** [comment]
Ahí anduvo. Lo que me pide hacer es corroborar que se borre el producto en la fila correspondiente. Éste es el código:

```
def test_eliminación_fila_correspondiente(self):
        #Creo un producto
        prod = Product(id= 1, name= 'Tenedor', price= 50)
        db.session.add(prod)

        #Creo una orden
        order = Order(id= 1)
        db.session.add(order)

        orderProduct = OrderProduct(order_id= 1, product_id= 1, quantity= 1, product= prod)
        db.session.add(orderProduct)
        db.session.commit()

        driver = self.driver
        driver.get(self.baseURL)

        time.sleep(5)

        delete_product_button = driver.find_element_by_xpath('//*[@id="orders"]/table/tbody/tr/td[6]/button[2]')
        delete_product_button.click()
        
        time.sleep(5)
```

Me falta la parte del assert. Mi idea es crear dos productos, borrar uno y fijarme si borró correctamente. ¿Sería eso?

**Comment by RodrigoJacznik** [comment]
Si, no está mal.
Podrías controlar que en la base de datos se haya borrado el producto correcto

**Comment by luisuran** [comment]
¿Qué te parece ésto?

`    def test_eliminación_fila_correspondiente(self):
        #Creo los productos
        prod = Product(id= 1, name= 'Tenedor', price= 50)
        db.session.add(prod)
        prod2 = Product(id= 2, name= 'Calabaza', price= 30)
        db.session.add(prod)

        #Creo una orden
        order = Order(id= 1)
        db.session.add(order)

        #Añado los productos a la orden
        orderProduct = OrderProduct(order_id= 1, product_id= 1, quantity= 1, product= prod)
        db.session.add(orderProduct)
        orderProduct = OrderProduct(order_id= 1, product_id= 2, quantity= 1, product= prod2)
        db.session.add(orderProduct)
        db.session.commit()

        driver = self.driver
        driver.get(self.baseURL)

        time.sleep(1)

        delete_product_button = driver.find_element_by_xpath('//*[@id="orders"]/table/tbody/tr/td[6]/button[2]')
        delete_product_button.click()
        
        time.sleep(1)

        op = OrderProduct.query.all()

        # Verifica que se haya borrado el producto de la lista de productos
        self.assertEqual(len(op), 1, "No se borró el producto")

        #Verifica que se haya borrado el producto correcto
        self.assertNotEqual(op[0].product, prod, "No se borró el producto correcto")`

**Comment by ivanduva** [comment]
Ahí va Luis, está bien!
