### ISSUE TITLE
No reconoce el test

### ISSUE THREAD

**Issue by DiegoDelgado95** [frlp-utn-is-2018/orderingg#58]
Hola, cree el test para la cantidad de orderProducto, pero cuando tiro el comando "pytest test_unit.py" desde el cmd parado en la carpeta orderingg/test,  solo reconoce 2 items que ya estan, no me reconoce los cambio que estoy haciendo en el archivo

**Comment by RodrigoJacznik** [comment]
Hola
Subí el contenido del archivo así lo miro

**Comment by DiegoDelgado95** [comment]
Ya tire push de la rama feature/#9  en el archivo test_unit el test "Cantidad_Negativa" no reconoce el cambio

**Comment by RodrigoJacznik** [comment]
Que push? la verdad que no entendí.

**Comment by DiegoDelgado95** [comment]
El push para que veas el archivo como esta, aca te dejo como esta escrito el test


def Cantidad_Negativa(self):
        Ord = Orden(id=1)
        db.session.add(Ord)

        pro = Product(id=1, name='Plato', price=10)
        db.session.add(Pro)

        OrderProduct = OrderProduct(order_id=1, product_id=1, quantity=-1, product=pro)
        db.session.add(OrderProduct)
        db.session.commit()

        resp = self.client.get('/order/1/product/1')
        self.assert200(resp, "No existe Orden")

**Comment by RodrigoJacznik** [comment]
ahh, pasame el link del repo asi me lo bajo

**Comment by DiegoDelgado95** [comment]
github.com/luchoCap/orderingg

**Comment by RodrigoJacznik** [comment]
los nombres de los test tienen que empezar con la palabra `test_`.
En tu caso seria `test_cantidad_negativa`

**Comment by DiegoDelgado95** [comment]
Ahhh listo, ya funciona y corre bien, gracias!
