### ISSUE TITLE
No encuentro/existe totalprice en OrderProducto

### ISSUE THREAD

**Issue by titiloxx** [frlp-utn-is-2018/orderingg#60]
Hola, como dice el titulo, no logro encontrar un atributo "totalprice"  en orderProduct.
Mi enunciado dice: "Hacer un test de unidad para verificar que el valor de totalPrice de la clase OrderProduct se calcule correctamente"

El tema es, si no me equivoco, que el precio total se calcula en el frontend, no es una variable que exista fuera de el.
Aca dejo la linea donde se calcula y se inserta al html: 
`const totalPrice = state.selectedProduct.price * state.quantity;
            $totalPrice.innerHTML = `Precio total: $ ${totalPrice}``

Ese seria el problema 
Gracias!

**Comment by RodrigoJacznik** [comment]
Si, no hay problema con eso tenes que agarrar el valor y controlar que se calcule bien

**Comment by titiloxx** [comment]
Joya, entonces es un test de integracion lo que tengo que hacer no?

**Comment by RodrigoJacznik** [comment]
Cuál es el enunciado?

**Comment by RodrigoJacznik** [comment]
Recién me fijé en el modelo y existe la propiedad `orderPrice`. Si el enunciado dice que es de unidad lo vas a poder hacer.

**Comment by titiloxx** [comment]
Excelente, voy a buscar la propiedad mejor entonces. Gracias
