### ISSUE TITLE
Error en la definición de los test

### ISSUE THREAD

**Issue by TeoBotta** [frlp-utn-is-2018/orderingg#64]
Buenas, tengo el test de integración ya hecho, y hasta hace un rato andaba lo más bien. Por las dudas lo volví a correr antes de commitearlo y ahora me aparece el siguiente error:

  def test_negativa_quantity(self):
E       fixture 'self' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

Cuál se supone sería el problema? Desde ya, gracias

**Comment by RodrigoJacznik** [comment]
como estas corriendo los test?

**Comment by TeoBotta** [comment]
Desde el directorio orderingg con el comando pytest. Es el único test en donde me indica ese error, todos los otros están definidos de manera semejante.

**Comment by RodrigoJacznik** [comment]
como es el test? 
No quedo bien formateado lo que me mandaste

**Comment by TeoBotta** [comment]
El código del test es el siguiente:

```python
def test_negativa_quantity(self):
	    # Creo un producto para que aparezca en el scroll
	    p = Product(id=1, name="Vaso", price=50)
	    db.session.add(p)
	    o = Order(id=1)
	    db.session.add(o)
	    db.session.commit()
	    driver = self.driver
	    driver.get(self.baseURL)
	    # Clickeo en el botón 'Agregar'
	    add_product_button = driver.find_element_by_xpath('/html/body/main/div[1]/div/button')
	    add_product_button.click()
	    # Clickeo en la selección de producto
	    select_product = driver.find_element_by_id('select-prod')
	    select_product.click()
	    # Clickeo en la opción 2 de la lista
	    opcion_seleccionada = driver.find_element_by_xpath('//*[@id="select-prod"]/option[2]')
	    opcion_seleccionada.click()
	    # Le ingreso una cantidad negativa
	    cantidad_product = driver.find_element_by_id('quantity')
	    cant = cantidad_product.send_keys("-3")
	    # Clickeo en el botón de guardado
	    save_button = driver.find_element_by_id('save-button')
	    save_button.click()
	    #--Verificar si el producto anterior aparece en el modal
	    time.sleep(2)
	    # Verifica que en la lista de productos no haya
	    p = Product.query.all()
	    self.assertEqual(len(p), 0, "Hay productos cargados")
```

Lo que mandé al principio del issue es lo que devuelve el error en consola.

**Comment by RodrigoJacznik** [comment]
El test esta bien, no te hagas drama. De ultima lo reviso cuando lo bajo. 
Pushea tranquilo.
Cierro el issue

**Comment by TeoBotta** [comment]
Joya, muchas gracias!
