### ISSUE TITLE
Consulta por Test de Funcionamiento GET

### ISSUE THREAD

**Issue by Alexissiminkowich** [frlp-utn-is-2018/orderingg#69]
En el assert, es correcto usarlo así (antes inicie y cargue un producto en la bd):

respGET=self.client.get('/order/1/product/1')
self.assert200(respGET, "No existe la orden o el producto")

Gracias

**Comment by RodrigoJacznik** [comment]
Si, no se bien que test es, pero si se trata de alguno que modifica la base de datos mediante la api lo correcto seria testear que el cambio sea correcto en la DB.

**Comment by ivanduva** [comment]
Alexis, ese assert está bien. Faltaría fijarte que efectivamente devuelva la info que esperás. Por ejemplo, si creaste una orden con el producto "Mesa" de precio 5000 y una cantidad de 4, tenés que chequear que esos datos aparezcan también en el contenido de la respuesta.

**Comment by Alexissiminkowich** [comment]
Ahi subi un cambio con respecto al test de GET.
Lo ejecuto y tira lo siguiente:

Equipo@Equipo-PC MINGW32 ~/Desktop/ING DE SOFTWARE/orderingg (test#1.b)
$ pytest
============================= test session starts =============================
platform win32 -- Python 3.4.0, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: C:\Users\Equipo\Desktop\ING DE SOFTWARE\orderingg, inifile:
collected 4 items

test\test_unit.py F...                                                   [100%]

================================== FAILURES ===================================
_____________________ OrderingTestCase.test_GET_function ______________________

self = <test.test_unit.OrderingTestCase testMethod=test_GET_function>

    def test_GET_function(self):
        # Inicio la Orden y cargo en la BD
        o = Order(id=1)
        db.session.add (o)

        # Inicio el Producto y cargo en la BD
        p = Product(id=1, name='Silla', price=200)
        db.session.add(p)

        #Inicio la Order del Producto y cargo en la BD
        orderProduct = OrderProduct(order_id=1, product_id=1, quantity=8, product=p)
        db.session.add(orderProduct)

        db.session.commit()

        #Consulto la Orden
        respGET=self.client.get('/order/1')

        #Corroboro que se halla cargado la Orden
        self.assert200(respGET, "No existe la orden")

        #Consulto el producto
        product = json.loads(respGET.data)

        #Corroboro que se halla cargado el Producto
>       self.assertEqual(len(product),1, "No se cargo el producto")
E       AssertionError: 3 != 1 : No se cargo el producto

test\test_unit.py:100: AssertionError
===================== 1 failed, 3 passed in 5.65 seconds ======================


Realiza bien el assert, pero no se porque trae un 3 (?) como lo comparo con un 1 tira el error. Sera porque hasta ese momento, en la BD de test, ya se crearon 3 productos, por los demas test???

Saludos

**Comment by RodrigoJacznik** [comment]
Hola,

Esta bien el test, fíjate que trae el data con un print

**Comment by Alexissiminkowich** [comment]
El print me da:

---------------------------- Captured stdout call -----------------------------
{'orderPrice': 1600.0, 'products': [{'price': 200.0, 'name': 'Silla', 'totalPrice': 1600.0, 'quantity': 8, 'id': 1}], 'id': 1}
===================== 1 failed, 3 passed in 5.81 seconds ======================

Osea, son 3 elementos, el orderPrice, el products y el id, por eso devuelve 3 no? es correcto?

**Comment by RodrigoJacznik** [comment]
Exacto, es un diccionario con 3 claves por eso len retorna 3. 
No se muy bien que es lo que tenes que testear.

**Comment by Alexissiminkowich** [comment]
b. Hacer un test de unidad para probar el funcionamiento del método GET en el endpoint /order/<pk_order>/product/<pk_product>. 

Ese es el inciso. Por eso hago un assert para el get viendo que funciona y luego el assert para ver si realmente se cargo el articulo, como dijo Ivan

**Comment by RodrigoJacznik** [comment]
Bien, fíjate que en la url te falta esta parte `/product/<pk_product>`

**Comment by Alexissiminkowich** [comment]
Ya esta, agregue /product/1 y cambie la consulta del dato:

Esta linea: 
data = json.loads(respGET.data)

por esta:
data = Product.query.all()

el print me tira:
---------------------------- Captured stdout call -----------------------------
[Silla]

y ahora el assert asi:
self.assertEqual(len(data),1, "No se cargo el producto")

Y listo, funciona. Gracias a ambos!

**Comment by RodrigoJacznik** [comment]
Ojo que si sacas el get no estás testeando el get

**Comment by Alexissiminkowich** [comment]
Sisi, hay otro assert para el GET, asi quedo

def test_GET_function(self):
        # Inicio la Orden y cargo en la BD
        o = Order(id=1)
        db.session.add (o)

        # Inicio el Producto y cargo en la BD
        p = Product(id=1, name='Silla', price=200)
        db.session.add(p)

        #Inicio la Order del Producto y cargo en la BD
        orderProduct = OrderProduct(order_id=1, product_id=1, quantity=8, product=p)
        db.session.add(orderProduct)

        db.session.commit()

        #Consulto la Orden
        respGET=self.client.get('/order/1/product/1')
        
        #Corroboro que se halla cargado la Orden
        self.assert200(respGET, "No existe la orden")

        #Consulto el producto
        data = Product.query.all()
        print(data)
        
        #Corroboro que se halla cargado el Producto
        self.assertEqual(len(data),1, "No se cargo el producto")

**Comment by RodrigoJacznik** [comment]
Casi, podes comprobar que el producto en respGET.data sea correcta
