### ISSUE TITLE
Problemas con git

### ISSUE THREAD

**Issue by jiperdiguero** [frlp-utn-is-2018/orderingg#70]
Hola,

estoy teniendo este problemas con algunos archivos que te generaron con la realización de los test de unidad e integración. Esto es lo que me reporta GIT:

$ git status
On branch re-test/#1-unit
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    .pytest_cache/v/cache/lastfailed
        deleted:    .pytest_cache/v/cache/nodeids
        deleted:    debug.log

no changes added to commit (use "git add" and/or "git commit -a")

jperdiguero@LAPTOP-HLR3DBA2 MINGW64 ~/Documents/GitHub/orderingg/test (re-test/#1-unit)
$ git add/rm -pytest_cache/v/cache/lasfailed
warning: failed to restrict file handles (2)

handle #0: 00000000000003ec (type 3, handle info (1) 7ff9
handle #1: 00000000000003f0 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'add/rm' is not a git command. See 'git --help'.

????
Julián

**Comment by RodrigoJacznik** [comment]
Buenas, add/rm dice que uses uno u otro no los 2 juntos.
Esos archivos no los tenes que pushear, los podes eliminar tranquilamente (rm).

Lo ideal es agregarlo al gitignore.

**Comment by jiperdiguero** [comment]
Si lo voy a ignorar, realmente probé de todas formas e igual siguen apareciendo: borrados, modificados
incluso todo junto.. jaja

**Comment by RodrigoJacznik** [comment]
Capaz le pifiaste en algún comando.

`git rm` no funciona si el archivo no esta trackeado (si nunca lo agregaste).
Si no esta trackeado lo tenes que borrar con el comando del sistema operativo (`rm` a secas si estas en git bash)
