### ISSUE TITLE
Actividad 4 - bugfix de Flake8

### ISSUE THREAD

**Issue by Alexissiminkowich** [frlp-utn-is-2018/orderingg#81]
Buenas noches

Ya realice varios bugfix de diversos tipos de bugs, son suficientes para la actividad o continuo haciendo?

Saludos

**Comment by RodrigoJacznik** [comment]
Como quieras, si ya cumpliste el mínimo esta bien.

Aclaración: no son bugs lo que se arregló.

Saludos.

**Comment by Alexissiminkowich** [comment]
Bien bien.

Ahhhh me quede con la costumbre de bugfix de las actividades pasadas. Estos son solo fix, correcto?

Saludos

**Comment by RodrigoJacznik** [comment]
Si, probablemente es un mejor termino.
