### ISSUE TITLE
Coverage - Punto b

### ISSUE THREAD

**Issue by Alexissiminkowich** [frlp-utn-is-2018/orderingg#90]
Inciso:
¿Cómo cambiaría el porcentaje de coverage si eliminaramos el método totalPrice() de la clase OrderProduct?

La elimino y me da el siguiente resultado, esta bien?

$ coverage report
app\models.py   NotPython: Couldn't parse 'C:\Users\Equipo\Desktop\ING DE SOFTWARE\orderingg\app\models.py' as Python source: 'invalid syntax' at line 89
Name              Stmts   Miss Branch BrPart  Cover
---------------------------------------------------
app\__init__.py      14      8      0      0    43%
app\routes.py        55     52     24      0     4%
---------------------------------------------------
TOTAL                69     60     24      0    10%

**Comment by RodrigoJacznik** [comment]
Como respondí en el issue anterior, es un punto para reflexionar.
Importa más el porque cambia el porcentaje que el como cambia.
Los porcentajes dependen del código, cada grupo debería tener distintos resultados.

**Comment by Alexissiminkowich** [comment]
*ACTIVIDAD 4*

*EJERCICIO DE COVERAGE*



Alumno: Siminkowich Alexis



*Enunciado:*

Correr *coverage*, subir la imagen que genera y responder las siguientes
preguntas respondiendo este email:

a.       ¿Cómo cambiaría el porcentaje de *coverage* si definiéramos una
nueva función en *routes.py *con una url nueva y con el método *GET* que
retorne cualquier información?

b.      ¿Cómo cambiaría el porcentaje de *coverage *si elimináramos el
método *totalPrice()* de la clase *OrderProduct*?

c.       ¿Cómo cambiaría el porcentaje de *coverage* si elimináramos un
test?





Resultado antes de las actividades de “coverage report”:



$ coverage report

Name              Stmts   Miss Branch BrPart  Cover

---------------------------------------------------

app\__init__.py      14      0      0      0   100%

app\models.py        31      4      4      0    77%

app\routes.py        55     30     24      3    41%

---------------------------------------------------

TOTAL               100     34     28      3    57%



a)

Si agregáramos una nueva función en routes.py con una url nueva y con el
método GET, en el resultado de coverage report, en la línea de
app\routes.py y columna Cover, su porcentaje aumentaría. Ya que se agrego
una nueva función y ahora routes.py tiene más cobertura.



b)



Al eliminar el método totalPrice() de OrderProduct se espera que el
porcentaje de models.py disminuya.

Da el siguiente resultado:



$ coverage report

app\models.py   NotPython: Couldn't parse 'C:\Users\Equipo\Desktop\ING DE
SOFTWARE\orderingg\app\models.py' as Python source: 'invalid syntax' at
line 89

Name              Stmts   Miss Branch BrPart  Cover

---------------------------------------------------

app\__init__.py      14      8      0      0    43%

app\routes.py        55     52     24      0     4%

---------------------------------------------------

TOTAL                69     60     24      0    10%



c)



Elimine el test_crear_producto() para realizar la prueba, como los test de
unidad utilizan routes.py y models.py, al eliminar un test, baja la
cobertura de ambos, por lo que bajan sus porcentajes.

Da el siguiente resultado:



$ coverage report

Name              Stmts   Miss Branch BrPart  Cover

---------------------------------------------------

app\__init__.py      14      0      0      0   100%

app\models.py        31      5      4      0    74%

app\routes.py        55     34     24      4    34%

---------------------------------------------------

TOTAL               100     39     28      4    52%

**Comment by RodrigoJacznik** [comment]
Envialo por mail
